// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0p9BovGXEt0dPmExAFvq8FMIZ5nH8ig',
    appId: '1:933505670343:android:0ca7189c79894fed5232e2',
    messagingSenderId: '933505670343',
    projectId: 'rkade-mynotes',
    storageBucket: 'rkade-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUlmdzWKuSD3UFKQNaK4P2ZqkQWc4j6M',
    appId: '1:933505670343:ios:f06f578d011de3505232e2',
    messagingSenderId: '933505670343',
    projectId: 'rkade-mynotes',
    storageBucket: 'rkade-mynotes.appspot.com',
    iosClientId:
        '933505670343-c3nhkrev5t1jf8t37h7mnr8v2amkejto.apps.googleusercontent.com',
    iosBundleId: 'eth.rakshitarora.mynotes',
  );
}
